<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EVOAUGI" failures="2" tests="12" name="ReTest" time="13.174" errors="0" timestamp="2022-11-06T19:59:56 EST">
  <testcase classname="ui.Testng.retryTestCases" name="test0" time="0.011"/>
  <testcase classname="ui.Testng.retryTestCases" name="test1" time="5.637">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="ui.Testng.retryTestCases" name="test1" time="0.647">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="ui.Testng.retryTestCases" name="test1" time="0.497">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="ui.Testng.retryTestCases" name="test1" time="0.445">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="ui.Testng.retryTestCases" name="test1" time="0.726">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ui.Testng.retryTestCases.test1(retryTestCases.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="ui.Testng.retryTestCases" name="test2" time="1.015">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="ui.Testng.retryTestCases" name="test2" time="1.019">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="ui.Testng.retryTestCases" name="test2" time="1.007">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="ui.Testng.retryTestCases" name="test2" time="1.009">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="ui.Testng.retryTestCases" name="test2" time="1.015">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method ui.Testng.retryTestCases.test2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method ui.Testng.retryTestCases.test2() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="ui.Testng.retryTestCases" name="standby" time="0.0">
    <skipped/>
  </testcase> <!-- standby -->
</testsuite> <!-- ReTest -->
